"""Dashboard services module."""

from .state import (
    events,
    ws_clients,
    start_time,
    detection_store,
    health_checker,
    session_manager,
    orchestrator,
    ab_test_manager,
    model_registry,
    config_path,
    reid_engine,
    timeseries_engine,
    auto_annotator,
    report_generator,
    behavior_analyzer,
    anomaly_baseline,
    reasoning_chain,
    rag_retriever,
    set_detection_store,
    set_health_checker,
    set_session_manager,
    set_orchestrator,
    set_ab_test_manager,
    set_model_registry,
    set_config_path,
    set_reid_engine,
    set_timeseries_engine,
    set_auto_annotator,
    set_report_generator,
    set_behavior_analyzer,
    set_anomaly_baseline,
    set_reasoning_chain,
    set_rag_retriever,
    inject_from_central,
)
from .demo_data import (
    get_demo_models,
    get_demo_behavior_events,
    get_demo_baselines,
    get_demo_anomaly_scores,
    get_demo_vlm_guidance,
    get_demo_reid_tracks,
    get_demo_reid_track,
    get_demo_annotated_samples,
    get_demo_users,
    add_demo_user,
    update_demo_user,
    delete_demo_user,
)
from .validators import validate_config

__all__ = [
    # State
    "events",
    "ws_clients",
    "start_time",
    "detection_store",
    "health_checker",
    "session_manager",
    "orchestrator",
    "ab_test_manager",
    "model_registry",
    "config_path",
    # v2: Analytics
    "reid_engine",
    "timeseries_engine",
    "auto_annotator",
    "report_generator",
    # v2: Intelligence
    "behavior_analyzer",
    "anomaly_baseline",
    "reasoning_chain",
    "rag_retriever",
    # Setters
    "set_detection_store",
    "set_health_checker",
    "set_session_manager",
    "set_orchestrator",
    "set_ab_test_manager",
    "set_model_registry",
    "set_config_path",
    "set_reid_engine",
    "set_timeseries_engine",
    "set_auto_annotator",
    "set_report_generator",
    "set_behavior_analyzer",
    "set_anomaly_baseline",
    "set_reasoning_chain",
    "set_rag_retriever",
    "inject_from_central",
    # Demo data
    "get_demo_models",
    "get_demo_behavior_events",
    "get_demo_baselines",
    "get_demo_anomaly_scores",
    "get_demo_vlm_guidance",
    "get_demo_reid_tracks",
    "get_demo_reid_track",
    "get_demo_annotated_samples",
    "get_demo_users",
    "add_demo_user",
    "update_demo_user",
    "delete_demo_user",
    # Validators
    "validate_config",
]
