"""Dashboard services module."""

from .state import (
    events,
    ws_clients,
    start_time,
    detection_store,
    health_checker,
    session_manager,
    orchestrator,
    ab_test_manager,
    model_registry,
    config_path,
    set_detection_store,
    set_health_checker,
    set_session_manager,
    set_orchestrator,
    set_ab_test_manager,
    set_model_registry,
    set_config_path,
    inject_from_central,
)
from .demo_data import (
    get_demo_models,
    get_demo_behavior_events,
    get_demo_baselines,
    get_demo_anomaly_scores,
    get_demo_vlm_guidance,
    get_demo_reid_tracks,
    get_demo_reid_track,
    get_demo_annotated_samples,
    get_demo_users,
    add_demo_user,
    update_demo_user,
    delete_demo_user,
)
from .validators import validate_config

__all__ = [
    # State
    "events",
    "ws_clients",
    "start_time",
    "detection_store",
    "health_checker",
    "session_manager",
    "orchestrator",
    "ab_test_manager",
    "model_registry",
    "config_path",
    "set_detection_store",
    "set_health_checker",
    "set_session_manager",
    "set_orchestrator",
    "set_ab_test_manager",
    "set_model_registry",
    "set_config_path",
    "inject_from_central",
    # Demo data
    "get_demo_models",
    "get_demo_behavior_events",
    "get_demo_baselines",
    "get_demo_anomaly_scores",
    "get_demo_vlm_guidance",
    "get_demo_reid_tracks",
    "get_demo_reid_track",
    "get_demo_annotated_samples",
    "get_demo_users",
    "add_demo_user",
    "update_demo_user",
    "delete_demo_user",
    # Validators
    "validate_config",
]
